org: ds
space: csaa-mobile-dev
space-developer:
  ldap_users: []
  users:
  - ci-mobile
  - dumitru.gudima@csaa.com
  - brandon.gray@csaa.com
  - anthony.lee@csaa.com
  - dhirender.kumar@csaa.com
  - samar.kumar@csaa.com
  - brant.stuns@csaa.com
  - adam.mott@csaa.com
  - john.dee@csaa.com
  - pawel.bardzinski@csaa.com
  - neal.rutta@csaa.com
  ldap_group: ""
space-manager:
  ldap_users: []
  users: []
  ldap_group: ""
space-auditor:
  ldap_users: []
  users: []
  ldap_group: ""
allow-ssh: true
enable-space-quota: false
memory-limit: 10240
instance-memory-limit: -1
total-routes: 10
total-services: -1
paid-service-plans-allowed: false
enable-security-group: false
enable-remove-users: true
